### ISSUE TITLE
Possibility of absence of any of the sensors.

### ISSUE THREAD

**Issue by Xirate** [art2limit/Compass-View#10]
Hi.

I'm developing an app using your CompassView. I noticed, that if hardware doesn't have magnetic sensor it can't work and it won't display. In my case, I added:
if (magneticFieldSensor == null || accelerometerSensor == null) {
        throw new NoSensorException();
}
to the CompassSensorManager constructor and exception looks like this:
public class NoSensorException extends Exception {
}
Thus I can check if CompassView can actually work on the device and select other layout if it can't.

**Comment by artemiygrn** [comment]
hi, and what your offer to the library? :)

**Comment by Xirate** [comment]
I think you could add the same. If a user tries to use CompassView in app it will create a crash manageable for developers. Tests will catch it and they will fix it. I had no idea why CompassView is not rendering until I noticed the lack of sensor. I think it would help, otherwise you can add proper sentence to the documentation.

**Comment by Xirate** [comment]
I won't fork the library, or sth, because I'm noob with github and I don't want to mess up anything :)

**Comment by artemiygrn** [comment]
> If a user tries to use CompassView in app it will create a crash manageable for developers

I think some developers may skip this case and make crash on users in production. Empty view not a big deal, but developer should know about this

> I think it would help, otherwise you can add proper sentence to the documentation

yep, this correct way, and library need gradle-dependency and some rebuild. I may upgrade library on this weekends. If you have more some ideas — please feel free to write

**Comment by Xirate** [comment]
Actually, I also cheated on one thing. I wanted CompassView to point some place while the user is moving (some sort of waypoint tracker, like in games - you have an arrow that points you towards destination). I had to do it by reinitializing CompassView with updated location, maybe add something like setCurrentLocation() and make it reevaluate the azimuth

**Comment by art2limit** [comment]
Library rebuild complete, please create new issue if you anything want

For functionality that you suggest of start of issue please use CompassSensorManager.isDeviceCompatible()
